### ISSUE TITLE
fs-api.js: make `projectRoot` configurable? Compatibility issues with yarn workspaces

### ISSUE THREAD

**Issue by bjrn** [ADARTA/netlify-cms-components#2]
I'm using the `netlify-cms-backend-fs` for a gatsby website. However the repo is a yarn workspace containing multiple sites. When using netlify-cms in prod mode (sync with github) I need to make content paths root relative, eg. `/website-a/src/content/something/` 

when starting up in dev mode, `netlify-cms-backend-fs` reports that site root is `Users/blah/dev/website-a/`, and therefore paths in config.yml are rendered invalid (`/website-a/website-a/src/content/...`).

Suggestion: make `projectRoot` in `fs-api.js` configurable?

**Comment by talves** [comment]
The good news is I made it configurable already. I considered this case, just have not documented.

Be careful on testing this, because I have not tested it 100%.

In each Gatsby website mono-repo put in the following value in your `package.json`

    "fileSystemPath": "../"

This should accomplish: `siteRoot.dir = path.join(projectRoot, relPath)`

I am wondering if I should call this `Repository path` rather than site path 😜 or maybe "API path" would be better.

**Comment by bjrn** [comment]
alright, will try it out, thanks!

**Comment by bjrn** [comment]
worked fine, thanks!
