### ISSUE TITLE
netlify-cms-backend-fs doesn't work properly with netlify-cms-app >=2.11.0

### ISSUE THREAD

**Issue by smashercosmo** [ADARTA/netlify-cms-components#20]
Works with 2.10.1, but with 2.11.0 when trying to upload an image I'm getting
```
TypeError: Cannot read property 'replace' of undefined
```
```
Uncaught (in promise) TypeError: Cannot set property 'scrollTop' of null
```

**Comment by talves** [comment]
Not sure what is going on with these without a test case. I guess they made a breaking change in the api without bumping it on a major release.

Since it looks like `netlify-cms` will start handling local file-system updates internally, this plugin will more than likely get deprecated. I will leave this open until we know for sure the new solution works.

**Comment by talves** [comment]
Closing: https://github.com/ADARTA/netlify-cms-components/issues/21#issuecomment-700221094
